package ru.yandex.taskmanager.api;

public enum Endpoint {
	GET_ALL_TASKS, GET_ALL_EPICTASKS, GET_ALL_SUBTASKS,
	GET_TASK_BY_ID, GET_EPICTASK_BY_ID, GET_SUBTASK_BY_ID,
	ADD_UPDATE_TASK, ADD_UPDATE_EPICTASK, ADD_UPDATE_SUBTASK,
	DELETE_TASK_BY_ID, DELETE_EPICTASK_BY_ID, DELETE_SUBTASK_BY_ID,
	DELETE_ALL_TASKS, DELETE_ALL_EPICTASKS, DELETE_ALL_SUBTASKS,
	GET_SUBTASKS_FROM_EPIC,
	GET_HISTORY,
	GET_PRIORITIZED_TASKS,
	GET_ALL_TASKS_EPICTASKS_SUBTASKS,
	UNKNOWN
}